no.nav:
  security:
    jwt:
      issuer:
        tokenx:
          discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
          accepted_audience: ${TOKEN_X_CLIENT_ID}

  scheduled:
    utgått-cache: 300000 # 5 minutter

  mine-sider:
    psb-soknad:
      link: ${PSB_SOKNAD_URL}
      tittel: ${PSB_SOKNAD_TITTEL}
    psb-endringsmelding:
      link: ${PSB_ENDRINGSMELDING_URL}
      tittel: ${PSB_ENDRINGSMELDING_TITTEL}
    pleiepenger-livets-slutt:
      link: ${PLEIEPENGER_LIVETS_SLUTT_URL}
      tittel: ${PLEIEPENGER_LIVETS_SLUTT_TITTEL}
    omsorgspenger-utvidet-rett:
      link: ${OMSORGSPENGER_UTVIDET_RETT_URL}
      tittel: ${OMSORGSPENGER_UTVIDET_RETT_TITTEL}
    omsorgspenger-midlertidig-alene:
      link: ${OMSORGSPENGER_MIDLERTIDIG_ALENE_URL}
      tittel: ${OMSORGSPENGER_MIDLERTIDIG_ALENE_TITTEL}
    omsorgspenger-utbetaling-arbeidstaker:
      link: ${OMSORGSPENGER_UTBETALING_ARBEIDSTAKER_URL}
      tittel: ${OMSORGSPENGER_UTBETALING_ARBEIDSTAKER_TITTEL}
    omsorgsdager-aleneomsorg:
      link: ${OMSORGSDAGER_ALENEOMSORG_URL}
      tittel: ${OMSORGSDAGER_ALENEOMSORG_TITTEL}
    omsorgspenger-utbetaling-snf:
      link: ${OMSORGSPENGER_UTBETALING_SNF_URL}
      tittel: ${OMSORGSPENGER_UTBETALING_SNF_TITTEL}
    ettersending:
      link: ${ETTERSENDING_URL}
      tittel: ${ETTERSENDING_TITTEL}
    ettersending-pleiepenger-sykt-barn:
      link: ${ETTERSENDING_PLEIEPENGER_SYKT_BARN_URL}
      tittel: ${ETTERSENDING_PLEIEPENGER_SYKT_BARN_TITTEL}
    ettersending-pleiepenger-livets-slutt:
      link: ${ETTERSENDING_PLEIEPENGER_LIVETS_SLUTT_URL}
      tittel: ${ETTERSENDING_PLEIEPENGER_LIVETS_SLUTT_TITTEL}
    ettersending-omp:
      link: ${ETTERSENDING_OMP_URL}
      tittel: ${ETTERSENDING_OMP_TITTEL}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

spring:
  application:
    name: # Settes i nais/<cluster>.json

  flyway:
    baselineOnMigrate: true
    enabled: true
    clean-on-validation-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 2
      connection-timeout: 1000
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    disable-swagger-default-url: true
    path: swagger-ui.html

krypto:
  passphrase: ${KRYPTO_PASSPHRASE}
